In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

df = pd.read_csv('../ums_viz.csv')
df_perf = pd.read_pickle('descriptions.pkl')
df_perf.columns.values[0] = 'perf_name'

df['perf_name'] = df['perf_name'].apply(lambda x: x.strip())
df_perf['perf_name'] = df_perf['perf_name'].apply(lambda x: x.strip())

df['per_seat'] = df['tck_amt']/df['num_seats']
df_group = df.groupby('perf_name')

# Add a whole bunch of new performance-level features

# mean ticket amount, number of seats, price per seat
df_tmp = df_group['tck_amt', 'num_seats', 'per_seat'].mean().reset_index()
df_tmp = df_tmp.rename(columns = {'tck_amt': 'mean_tck_amt', 'num_seats': 'mean_num_seats', 'per_seat': 'mean_per_seat'})

df_perf = pd.merge(df_perf, df_tmp, on='perf_name')

# max ticket amount, number of seats, price per seat
df_tmp = df_group['tck_amt', 'num_seats', 'per_seat'].max().reset_index()
df_tmp = df_tmp.rename(columns = {'tck_amt': 'max_tck_amt', 'num_seats': 'max_num_seats', 'per_seat': 'max_per_seat'})
df_perf = pd.merge(df_perf, df_tmp, on='perf_name')

# total number of seats
df_tmp = df_group['num_seats'].count().reset_index()
df_tmp = df_tmp.rename(columns = {'num_seats': 'count_tck_amt'})
df_perf = pd.merge(df_perf, df_tmp, on='perf_name')

print df_perf

                perf_name                                        description  \
0     The Infernal Comedy  John Malkovich makes his UMS debut portraying ...
1        Yuja Wang, piano  Chinese pianist Yuja Wang combines the spontan...
2     London Philharmonic  The London Philharmonic returns for its first ...
3        Hamburg Symphony  In 1971, French composer Olivier Messiaen was ...
4    Chicago Symphony Orc  Wind players of the Chicago Symphony come toge...
5    San Francisco Sympho  Michael Tilson Thomas and the San Francisco Sy...
6      Pavel Haas Quartet  “The world’s most exciting string quartet? Wel...
7        Ballet Preljocaj  Few audience members in attendance at Ballet P...
8             Joshua Bell  Often referred to as a “poet of the violin,” J...
9          Murray Perahia  In the more than 35 years he has been performi...
10    Mariinsky Orchestra  The Mariinsky Orchestra and Valery Gergiev ret...
11   Detroit Symphony Orc  A concert created to showcase Hill Auditorium’...
12   New York Philharmoni  The New York Philharmonic performs three diffe...
13        Artemis Quartet  “Their performances overflow with fullness of ...
14    Anne-Sophie Mutter,  With unparalleled distinction in the world of ...
15         Bobby McFerrin  Matchless vocal improviser with a breathtaking...
16          Alison Balsom  Experience one of the most distinctive and gro...
17     SITI: Trojan Women  SITI is committed to providing a place where t...
18         Audra McDonald  Audra McDonald has secured her place atop Broa...
19   Andras Schiff, piano  After his stunning performance of Bach’s Goldb...
20          Apollo's Fire  Fresh from their 2014 performance of Monteverd...
21    Joshua Bell, violin  Often referred to as a “poet of the violin,” J...
22   St Petersburg Philha  The St. Petersburg Philharmonic returns to Ann...
23    Israel Philharmonic  The Israel Philharmonic, along with their “Mus...
24   Akademie fur Alte Mu  The Akademie für Alte Musik Berlin began as a ...
25       Olga Kern, piano  Olga Kern was the 2001 Van Cliburn winner and ...
26      Kremerata Baltica  Born in Latvia, violinist Gidon Kremer has had...
27   Tara Erraught, mezzo  Her career was launched with an unexpected deb...
28   Denis Matsuev, piano  Anyone who attended last season’s concert by t...
29     Handel's Radamisto  A concert opera featuring Handel’s Radamisto w...
..                    ...                                                ...
113      Ensemble Basiani  Ensemble Basiani was created in 2000 with the ...
114  Jason Moran's Fats W  Pianist Jason Moran, a 2011 MacArthur “Genius”...
115  Dan Zanes and Friend  Dan Zanes & Friends are releasing Little Nut T...
116             Max Raabe  Dashing, dapper, and debonair, Max Raabe might...
117  NT - Last of the Hau  High-Definition Broadcasts from the National T...
118  NT - Timon of Athens  High-Definition Broadcasts from National Theat...
119   NT - Traveling Ligh  A new play by Nicholas Wright\n In a remote vi...
120         Colin Stetson  Born and raised in Ann Arbor, saxophonist Coli...
121      Fred Hersch Trio  Proclaimed by Vanity Fair as “the most arresti...
122   One Night in Bamako  In the midst of a military coup that has broug...
123   Alfredo Rodriguez &  A young pianist of astonishing virtuosity and ...
124    Beijing Guitar Duo  Meng Su and Yameng Wang are widely noted for t...
125  NT - One Man, Two Gu  Based on Goldoni’s The Servant of Two Masters ...
126     NT - Frankenstein  For the third year, UMS and the Michigan Theat...
127      NT - The Kitchen  In the kitchen of an enormous West End restaur...
128  NT - The Comedy of E  Dominic Cooke, director of the Royal Court The...
129  Mavericks All Access  As part of its centennial season, Michael Tils...
130           NT - People  High-Definition Broadcasts from the National T...
131       NT - This House  High-Definition Broadcasts from National Theat...
132  NT - The Curious Inc  High-Definition Broadcasts from the National T...
133       NT - Coriolanus  "High-Definition Broadcasts from National Thea...
134    Steve Lehman Octet  Steve Lehman is a “quietly dazzling saxophonis...
135         Asif Ali Khan  If the late, great Nusrat Fateh Ali Khan (1948...
136           DC: Hubbard  Hubbard Street Dance Chicago returns for a one...
137   FAM -Aspen Santa Fe  “Simply breathtaking,” proclaims the Chicago S...
138           James Blake  Twenty-four-year-old James Blake is a classica...
139       Breakin' Curfew  Ann Arbor area youth raise the curtain of the ...
140                 Fela!  His story inspired a nation. His music inspire...
141  DC: Ballet Preljocaj  Few audience members in attendance at Ballet P...
142     Diego - post perf  “Flamenco has to be suffered,” Diego El Cigala...

     mean_tck_amt  mean_num_seats  mean_per_seat  max_tck_amt  max_num_seats  \
0       72.092196        1.997354      37.194444        595.0             14
1       63.171001        2.003096      32.884830        460.0             23
2       77.771242        1.937255      40.968301       1000.0             50
3       62.176976        1.838933      34.027619        487.5             17
4      110.584576        1.914630      56.604253      14960.0            187
5       70.300088        1.840749      38.253759       2137.5             47
6       52.089516        1.725806      29.705914        220.5              7
7       56.356970        1.902251      28.629358        384.0             14
8      105.120187        2.039090      52.261669       1000.0             45
9       76.766534        1.833067      41.964217        476.0             12
10      80.922870        1.890315      43.796120        948.6             34
11      81.089651        1.923940      42.609165        712.5             26
12      95.682890        1.876645      50.111264       2000.0             50
13      51.917073        1.707317      30.052683        168.0              4
14      71.954034        1.726891      40.748319        300.0             12
15      69.369122        2.141271      31.684157        663.0             26
16      74.539385        1.994262      37.285369       3952.5             93
17      58.950668        1.789649      32.566694        336.0             10
18      76.869143        2.138901      35.627033       5567.5            131
19      64.036790        1.759943      36.694247        445.5             26
20      69.218880        1.785797      38.675808        760.0             38
21      87.117126        1.853801      46.860735        513.0             19
22     102.065249        1.953827      53.289793        816.0             20
23     118.710638        1.903546      61.866667       1360.0             20
24      79.020470        1.776846      45.072148        490.0             11
25      71.648664        1.883263      38.916737        607.5             27
26      68.807287        1.795547      39.363360        800.0             40
27      57.403125        1.682292      33.972917        188.0              6
28      60.334421        1.876842      32.754632        720.0             40
29      69.950187        1.691635      40.963421        260.0              6
..            ...             ...            ...          ...            ...
113     41.668776        1.789030      23.308017        175.0              6
114     63.348214        2.125000      29.690179        350.0             16
115     22.422222        2.080556      11.000000         80.0             10
116     63.353834        2.166134      28.801597        900.0             25
117     37.318182        1.909091      19.545455         88.0              4
118     37.945205        2.095890      18.739726        240.0             20
119     33.205882        1.823529      17.852941         72.0              4
120     39.094828        1.887931      21.314655        180.0             10
121     55.047337        1.852071      30.337278        200.0              5
122     62.621053        2.101754      31.010175        230.0             14
123     76.430534        2.408397      33.356870       2430.0             81
124     54.627027        1.864865      27.923552        210.0              5
125     34.698113        1.971698      17.012579        176.0              8
126     32.788991        1.729358      19.192661        154.0             11
127     33.325664        2.000000      16.200885        261.8             14
128     30.992593        1.777778      17.155556         88.0              4
129    108.571429        1.314286      82.857143        200.0              4
130     38.956522        1.985507      19.420290        132.0              6
131     39.904762        2.119048      18.571429        110.0              5
132     36.495868        1.917355      18.842975        132.0              6
133     35.393103        1.820690      19.668966         88.0              6
134     44.632124        1.797927      24.076425        140.0              4
135     65.335211        2.084507      31.080282        345.0             15
136      0.000000        2.058824       0.000000          0.0              4
137     14.167742        2.045161       8.258065         72.0             12
138     63.185868        1.913978      32.501997        320.0              8
139     72.892655        5.480226      14.203390       3920.0            392
140    117.428571        2.360000      46.628571       1425.0             19
141      0.000000        1.590909       0.000000          0.0              3
142     39.473684        2.631579      15.000000         90.0              6

     max_per_seat  count_tck_amt
0            75.0           1512
1            56.0            969
2            80.0           1530
3            65.0           1012
4           120.0           3151
5            85.0           4540
6            42.0            372
7            54.0           2977
8           100.0           1714
9            75.0           1252
10           85.0           1714
11           75.0           1604
12          100.0           3267
13           42.0            410
14           75.0           1190
15           60.0            991
16           65.0           1220
17           48.0            599
18           70.0           2275
19           70.0           1408
20           70.0           1732
21           80.0           1197
22           85.0            823
23          100.0            705
24           70.0            596
25           60.0            711
26           60.0            494
27           50.0            384
28           56.0            950
29           65.0            801
..            ...            ...
113          35.0            237
114          35.0            280
115          16.0            360
116          48.0            626
117          22.0             44
118          22.0             73
119          22.0             68
120          30.0            116
121          40.0            169
122          50.0            285
123          48.0            262
124          42.0            259
125          22.0            106
126          22.0            218
127          22.0            113
128          22.0            135
129         100.0             35
130          22.0             69
131          22.0             42
132          22.0            121
133          22.0            145
134          35.0            193
135          46.0            142
136           0.0             17
137          12.0            155
138          44.0            651
139          18.0            177
140          75.0            175
141           0.0             22
142          15.0             19

[143 rows x 9 columns]

In [124]:
# Extract bigram matrix
from sklearn.feature_extraction.text import CountVectorizer, ENGLISH_STOP_WORDS

vect = CountVectorizer(ngram_range=(1, 1), stop_words = ENGLISH_STOP_WORDS, min_df = 5)
X = vect.fit_transform(df_perf.description.values)

print X.shape

(143, 446)

In [125]:
# Latent Dirichlet Allocation

from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_topics=5)
y = lda.fit_transform(X)

def print_top_words(model, feature_names, n_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic #%d:" % topic_idx)
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-n_top_words - 1:-1]]))
    print

print_top_words(lda, vect.get_feature_names(), 20)

df_perf['topic'] = np.argmax(y, 1)

Topic #0:
ballet dance company program century ums new performance set dancers movement william chicago contemporary director art years works world thing
Topic #1:
music new york jazz times voice musical best year heart album contemporary ums international known ensemble legendary singer debut traditions
Topic #2:
award winning director tour london theatre national high broadcasts presented theater definition michigan new partnership people history house play things
Topic #3:
music ums theatre national michigan london theater arbor ann american high new composers play partnership concert hall orchestra available broadcasts
Topic #4:
music quartet ums program performance debut work group world audiences concert string classical appearance years great returns new opera playing

In [126]:
df_perf.groupby('topic').describe()

             count_tck_amt  max_num_seats  max_per_seat   max_tck_amt  \
topic
0     count       8.000000       8.000000      8.000000      8.000000
      mean      770.875000      17.875000     33.250000    365.500000
      std       974.780479      14.681743     24.609812    405.904633
      min        17.000000       3.000000      0.000000      0.000000
      25%       121.750000       7.000000      9.000000     54.000000
      50%       527.000000      13.000000     48.000000    292.000000
      75%       905.000000      27.000000     51.000000    474.000000
      max      2977.000000      42.000000     54.000000   1188.000000
1     count      42.000000      42.000000     42.000000     42.000000
      mean      688.095238      31.190476     74.809524   1044.266667
      std       635.406987      36.518781    147.860389   1450.964274
      min        19.000000       4.000000     15.000000     80.000000
      25%       266.500000      10.000000     44.000000    273.000000
      50%       460.000000      18.000000     48.000000    422.500000
      75%       908.000000      35.500000     60.000000   1172.500000
      max      3267.000000     177.000000   1000.000000   6619.800000
2     count      10.000000      10.000000     10.000000     10.000000
      mean      348.600000      20.600000     28.800000    412.900000
      std       415.302621      26.230601     14.335659    522.357998
      min        44.000000       4.000000     22.000000     88.000000
      25%        75.250000       6.500000     22.000000    143.000000
      50%       108.000000       9.000000     22.000000    198.000000
      75%       431.500000      21.500000     22.000000    258.000000
      max      1186.000000      90.000000     56.000000   1620.000000
3     count      27.000000      27.000000     27.000000     27.000000
      mean      698.814815      35.370370     46.888889    751.159259
      std      1082.728108      74.682996     26.398329   1024.416139
      min        22.000000       4.000000     18.000000     72.000000
      25%       140.000000       6.500000     22.000000    157.000000
      50%       370.000000      17.000000     40.000000    350.000000
      75%       844.500000      26.500000     60.000000    882.300000
      max      5540.000000     392.000000    100.000000   4039.200000
4     count      56.000000      56.000000     56.000000     56.000000
      mean      844.839286      25.339286     53.964286    890.891071
      std       738.839453      26.723008     16.523223   1978.151389
      min       113.000000       4.000000     22.000000    165.600000
      25%       433.250000      10.000000     46.000000    294.000000
      50%       636.000000      18.500000     48.000000    519.000000
      75%      1019.250000      33.250000     60.000000    839.625000
      max      4540.000000     187.000000    120.000000  14960.000000

             mean_num_seats  mean_per_seat  mean_tck_amt
topic
0     count        8.000000       8.000000      8.000000
      mean         1.898167      19.689914     37.638334
      std          0.147214      14.384974     27.816925
      min          1.590909       0.000000      0.000000
      25%          1.863387       6.193548     10.625806
      50%          1.907226      27.895396     53.327766
      75%          1.987730      29.236940     57.388637
      max          2.058824      33.781414     63.442792
1     count       42.000000      42.000000     42.000000
      mean         2.056273      31.658722     64.767773
      std          0.195936      10.066202     20.601540
      min          1.776846      11.000000     22.422222
      25%          1.895161      26.589861     54.732105
      50%          2.059160      30.673727     63.160184
      75%          2.139156      34.749984     75.662425
      max          2.631579      74.530672    158.300686
2     count       10.000000      10.000000     10.000000
      mean         2.027584      21.882150     44.529328
      std          0.124495       6.686460     14.708342
      min          1.827273      17.012579     34.436364
      25%          1.929308      18.474501     35.787135
      50%          2.021421      19.080008     38.450864
      75%          2.142875      19.682175     42.363874
      max          2.182556      35.414402     75.728702
3     count       27.000000      27.000000     27.000000
      mean         2.070421      30.458159     59.962558
      std          0.725756      16.251101     26.965061
      min          1.314286      14.203390     25.926267
      25%          1.822110      18.864669     39.018249
      50%          1.903546      26.270270     52.867563
      75%          2.082478      37.274109     72.280278
      max          5.480226      82.857143    118.710638
4     count       56.000000      56.000000     56.000000
      mean         1.927809      33.108109     63.682272
      std          0.235534       7.033479     13.551694
      min          1.682292      16.200885     33.325664
      25%          1.778507      28.844426     55.885661
      50%          1.856544      32.660663     62.113908
      75%          1.987940      37.040958     70.332838
      max          2.885174      56.604253    110.584576